apiVersion: v1
kind: Service
metadata:
  name: momentum-controller
spec:
  ports:
    - name: web
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: momentum-controller
  type: ClusterIP
