apiVersion: v1
kind: Service
metadata:
  name: momentum-ui
spec:
  type: ClusterIP
  selector:
    app: momentum-ui
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
