apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: pgsql
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

