-- ************************* SqlDBM: PostgreSQL *************************
-- ****** Generated by SqlDBM: Momentum4, v60 by anton@odyssey.org ******



-- ************************************** user_type

CREATE TABLE user_type
(
    user_type_id   uuid NOT NULL,
    user_type_name varchar(255) NOT NULL,
    description    text NOT NULL,
    options        jsonb NULL,
    CONSTRAINT PK_501 PRIMARY KEY ( user_type_id )
);





-- ************************************** plugin

CREATE TABLE plugin
(
    plugin_id  uuid NOT NULL,
    meta       jsonb NOT NULL DEFAULT ('{}'),
    options    jsonb NULL,
    created_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_7 PRIMARY KEY ( plugin_id )
);








-- ************************************** asset_3d

CREATE TABLE asset_3d
(
    asset_3d_id uuid NOT NULL,
    meta        jsonb NOT NULL DEFAULT ('{}'),
    options     jsonb NULL DEFAULT '{}',
    created_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_2 PRIMARY KEY ( asset_3d_id )
);








-- ************************************** asset_2d

CREATE TABLE asset_2d
(
    asset_2d_id uuid NOT NULL,
    meta        jsonb NOT NULL DEFAULT ('{}'),
    options     jsonb NULL DEFAULT '{}',
    created_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_1 PRIMARY KEY ( asset_2d_id )
);








-- ************************************** "user"

CREATE TABLE "user"
(
    user_id      uuid NOT NULL,
    user_type_id uuid NOT NULL,
    profile      jsonb NOT NULL DEFAULT '{}',
    updated_at   timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_at   timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    options      jsonb NULL,
    CONSTRAINT PK_21 PRIMARY KEY ( user_id ),
    CONSTRAINT FK_14 FOREIGN KEY ( user_type_id ) REFERENCES user_type ( user_type_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_20 ON "user"
    (
     user_type_id
        );








-- ************************************** object_type

CREATE TABLE object_type
(
    object_type_id   uuid NOT NULL,
    asset_2d_id      uuid NULL,
    asset_3d_id      uuid NULL,
    object_type_name varchar(255) NOT NULL,
    category_name    varchar(255) NOT NULL,
    description      text NULL DEFAULT (''),
    options          jsonb NOT NULL,
    created_at       timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at       timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_19 PRIMARY KEY ( object_type_id ),
    CONSTRAINT FK_24 FOREIGN KEY ( asset_3d_id ) REFERENCES asset_3d ( asset_3d_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_24_1 FOREIGN KEY ( asset_2d_id ) REFERENCES asset_2d ( asset_2d_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX idx_21018_ind_796 ON object_type USING btree
    (
     object_type_name
        );

CREATE INDEX FK_17 ON object_type
    (
     asset_3d_id
        );

CREATE INDEX FK_18 ON object_type
    (
     asset_2d_id
        );








-- ************************************** attribute_type

CREATE TABLE attribute_type
(
    plugin_id      uuid NOT NULL,
    attribute_name varchar(255) NOT NULL,
    description    text NOT NULL DEFAULT (''),
    options        jsonb NULL,
    CONSTRAINT PK_4 PRIMARY KEY ( plugin_id, attribute_name ),
    CONSTRAINT FK_1 FOREIGN KEY ( plugin_id ) REFERENCES plugin ( plugin_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_3 ON attribute_type
    (
     plugin_id
        );








-- ************************************** user_user_attribute

CREATE TABLE user_user_attribute
(
    plugin_id      uuid NOT NULL,
    attribute_name varchar(255) NOT NULL,
    source_user_id uuid NOT NULL,
    target_user_id uuid NOT NULL,
    value          jsonb NOT NULL,
    options        jsonb NULL,
    CONSTRAINT PK_602 PRIMARY KEY ( plugin_id, attribute_name, source_user_id, target_user_id ),
    CONSTRAINT FK_19 FOREIGN KEY ( plugin_id, attribute_name ) REFERENCES attribute_type ( plugin_id, attribute_name ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_20 FOREIGN KEY ( source_user_id ) REFERENCES "user" ( user_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_21 FOREIGN KEY ( target_user_id ) REFERENCES "user" ( user_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_601 ON user_user_attribute
    (
     plugin_id,
     attribute_name
        );

CREATE INDEX FK_603 ON user_user_attribute
    (
     source_user_id
        );

CREATE INDEX FK_604 ON user_user_attribute
    (
     target_user_id
        );








-- ************************************** user_membership

CREATE TABLE user_membership
(
    member_of  uuid NOT NULL,
    user_id    uuid NOT NULL,
    value      json NULL,
    created_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    update_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_203 PRIMARY KEY ( member_of, user_id ),
    CONSTRAINT FK_16 FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_23 FOREIGN KEY ( member_of ) REFERENCES "user" ( user_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_202 ON user_membership
    (
     user_id
        );

CREATE INDEX FK_203 ON user_membership
    (
     member_of
        );








-- ************************************** user_attribute

CREATE TABLE user_attribute
(
    user_id        uuid NOT NULL,
    plugin_id      uuid NOT NULL,
    attribute_name varchar(255) NOT NULL,
    value          jsonb NOT NULL,
    options        jsonb NULL,
    CONSTRAINT PK_102 PRIMARY KEY ( user_id, plugin_id, attribute_name ),
    CONSTRAINT FK_12 FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_13 FOREIGN KEY ( plugin_id, attribute_name ) REFERENCES attribute_type ( plugin_id, attribute_name ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_101 ON user_attribute
    (
     user_id
        );

CREATE INDEX FK_103 ON user_attribute
    (
     plugin_id,
     attribute_name
        );








-- ************************************** object

CREATE TABLE object
(
    object_id      uuid NOT NULL,
    object_type_id uuid NOT NULL,
    owner_id       uuid NOT NULL,
    parent_id      uuid NOT NULL,
    asset_2d_id    uuid NULL,
    asset_3d_id    uuid NULL,
    options        jsonb NULL,
    "position"       jsonb NULL,
    updated_at     timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_at     timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_13 PRIMARY KEY ( object_id ),
    CONSTRAINT FK_6 FOREIGN KEY ( object_type_id ) REFERENCES object_type ( object_type_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_7 FOREIGN KEY ( parent_id ) REFERENCES object ( object_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_26 FOREIGN KEY ( asset_3d_id ) REFERENCES asset_3d ( asset_3d_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_8a FOREIGN KEY ( owner_id ) REFERENCES "user" ( user_id ),
    CONSTRAINT FK_25 FOREIGN KEY ( asset_2d_id ) REFERENCES asset_2d ( asset_2d_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_10 ON object
    (
     object_type_id
        );

CREATE INDEX FK_11 ON object
    (
     parent_id
        );

CREATE INDEX FK_12 ON object
    (
     asset_3d_id
        );

CREATE INDEX FK_8 ON object
    (
     owner_id
        );

CREATE INDEX FK_9 ON object
    (
     asset_2d_id
        );








-- ************************************** node_attribute

CREATE TABLE node_attribute
(
    plugin_id      uuid NOT NULL,
    attribute_name varchar(255) NOT NULL,
    value          jsonb NOT NULL,
    options        jsonb NULL,
    CONSTRAINT PK_6 PRIMARY KEY ( plugin_id, attribute_name ),
    CONSTRAINT FK_2 FOREIGN KEY ( plugin_id, attribute_name ) REFERENCES attribute_type ( plugin_id, attribute_name ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_5 ON node_attribute
    (
     plugin_id,
     attribute_name
        );








-- ************************************** user_object

CREATE TABLE user_object
(
    object_id  uuid NOT NULL,
    user_id    uuid NOT NULL,
    created_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    value      jsonb NULL,
    CONSTRAINT PK_3 PRIMARY KEY ( object_id, user_id ),
    CONSTRAINT FK_23_1 FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id ),
    CONSTRAINT FK_24_2 FOREIGN KEY ( object_id ) REFERENCES object ( object_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_1 ON user_object
    (
     user_id
        );

CREATE INDEX FK_2 ON user_object
    (
     object_id
        );








-- ************************************** object_user_attribute

CREATE TABLE object_user_attribute
(
    user_id        uuid NOT NULL,
    object_id      uuid NOT NULL,
    attribute_name varchar(255) NOT NULL,
    plugin_id      uuid NOT NULL,
    value          jsonb NULL,
    options        jsonb NULL,
    CONSTRAINT PK_402 PRIMARY KEY ( user_id, object_id, attribute_name, plugin_id ),
    CONSTRAINT FK_9 FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id ),
    CONSTRAINT FK_10 FOREIGN KEY ( plugin_id, attribute_name ) REFERENCES attribute_type ( plugin_id, attribute_name ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_11 FOREIGN KEY ( object_id ) REFERENCES object ( object_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_401 ON object_user_attribute
    (
     user_id
        );

CREATE INDEX FK_403 ON object_user_attribute
    (
     plugin_id,
     attribute_name
        );

CREATE INDEX FK_404 ON object_user_attribute
    (
     object_id
        );








-- ************************************** object_attribute

CREATE TABLE object_attribute
(
    plugin_id      uuid NOT NULL,
    attribute_name varchar(255) NOT NULL,
    object_id      uuid NOT NULL,
    value          jsonb NULL,
    options        jsonb NULL,
    CONSTRAINT PK_16 PRIMARY KEY ( plugin_id, attribute_name, object_id ),
    CONSTRAINT FK_3 FOREIGN KEY ( plugin_id, attribute_name ) REFERENCES attribute_type ( plugin_id, attribute_name ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_4 FOREIGN KEY ( object_id ) REFERENCES object ( object_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_14 ON object_attribute
    (
     plugin_id,
     attribute_name
        );

CREATE INDEX FK_15 ON object_attribute
    (
     object_id
        );







