-- ************************* SqlDBM: PostgreSQL *************************
-- ******** Generated by SqlDBM: Momentum4, v76 by rd@odyssey.org *******



-- ************************************** activity

CREATE TABLE activity
(
    activity_id uuid PRIMARY KEY,
    user_id     uuid NOT NULL,
    object_id   uuid NOT NULL,
    type        varchar(255) NOT NULL,
    data        jsonb NOT NULL,
    created_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT FK_ACTIVITY_USER FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ACTIVITY_OBJECT FOREIGN KEY ( object_id ) REFERENCES object ( object_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX ACTIVITY_USER_IDX ON activity
(
    user_id
);

CREATE INDEX ACTIVITY_OBJECT_IDX ON activity
(
    object_id
);

-- ************************************** user_activity

CREATE TABLE user_activity
(
    user_id     uuid NOT NULL,
    activity_id uuid NOT NULL,
    created_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    PRIMARY KEY ( user_id, activity_id ),
    CONSTRAINT FK_UA_ACTIVITY FOREIGN KEY ( activity_id ) REFERENCES activity ( activity_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_UA_USER FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX UA_ACTIVITY_IDX ON user_activity
(
    activity_id
);

CREATE INDEX UA_USER_IDX ON user_activity
(
    user_id
);

-- ************************************** object_activity

CREATE TABLE object_activity
(
    object_id   uuid NOT NULL,
    activity_id uuid NOT NULL,
    created_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    PRIMARY KEY ( object_id, activity_id ),
    CONSTRAINT FK_OA_OBJECT FOREIGN KEY ( object_id ) REFERENCES object ( object_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_OA_ACTIVITY FOREIGN KEY ( activity_id ) REFERENCES activity ( activity_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX OA_OBJECT_IDX ON object_activity
(
    object_id
);

CREATE INDEX OA_ACTIVITY_IDX ON object_activity
(
    activity_id
);
