-- ************************* SqlDBM: PostgreSQL *************************
-- ****** Generated by SqlDBM: Momentum4, v67 by anton@odyssey.org ******



-- ************************************** asset_3d_user

CREATE TABLE asset_3d_user
(
    asset_3d_id uuid NOT NULL,
    user_id     uuid NOT NULL,
    meta        jsonb NOT NULL,
    is_private     boolean NOT NULL DEFAULT true,
    updated_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_at  timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_103 PRIMARY KEY ( asset_3d_id, user_id ),
    CONSTRAINT FK_32 FOREIGN KEY ( asset_3d_id ) REFERENCES asset_3d ( asset_3d_id ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_33 FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX FK_110 ON asset_3d_user
    (
     asset_3d_id
        );

CREATE INDEX FK_111 ON asset_3d_user
    (
     user_id
        );







