// Code generated by musgen. DO NOT EDIT.

package cmath

import (
	"math"

	"github.com/ymz-ncnk/muserrs"
)

// MarshalMUS fills buf with the MUS encoding of v.
func (v Vec3) MarshalMUS(buf []byte) int {
	i := 0
	{
		uv := math.Float32bits(float32(v.X))
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	{
		uv := math.Float32bits(float32(v.Y))
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	{
		uv := math.Float32bits(float32(v.Z))
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	return i
}

// UnmarshalMUS parses the MUS-encoded buf, and sets the result to *v.
func (v *Vec3) UnmarshalMUS(buf []byte) (int, error) {
	i := 0
	var err error
	{
		var uv uint32
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 4 && b > 15 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint32(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint32(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		v.X = float32(math.Float32frombits(uv))
	}
	if err != nil {
		return i, muserrs.NewFieldError("X", err)
	}
	{
		var uv uint32
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 4 && b > 15 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint32(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint32(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		v.Y = float32(math.Float32frombits(uv))
	}
	if err != nil {
		return i, muserrs.NewFieldError("Y", err)
	}
	{
		var uv uint32
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 4 && b > 15 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint32(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint32(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		v.Z = float32(math.Float32frombits(uv))
	}
	if err != nil {
		return i, muserrs.NewFieldError("Z", err)
	}
	return i, err
}

// SizeMUS returns the size of the MUS-encoded v.
func (v Vec3) SizeMUS() int {
	size := 0
	{
		uv := math.Float32bits(float32(v.X))
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	{
		uv := math.Float32bits(float32(v.Y))
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	{
		uv := math.Float32bits(float32(v.Z))
		uv = (uv << 16) | (uv >> 16)
		uv = ((uv << 8) & 0xFF00FF00) | ((uv >> 8) & 0x00FF00FF)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	return size
}
