// Code generated by musgen. DO NOT EDIT.

package posbus

import (
	"github.com/momentum-xyz/ubercontroller/utils/umid"
	"github.com/ymz-ncnk/muserrs"
)

// MarshalMUS fills buf with the MUS encoding of v.
func (v AddPendingStake) MarshalMUS(buf []byte) int {
	i := 0
	{
		si := v.TransactionID.MarshalMUS(buf[i:])
		i += si
	}
	{
		si := v.OdysseyId.MarshalMUS(buf[i:])
		i += si
	}
	{
		si := v.Wallet.MarshalMUS(buf[i:])
		i += si
	}
	{
		si := v.Amount.MarshalMUS(buf[i:])
		i += si
	}
	{
		length := len(v.Comment)
		{
			uv := uint64(length)
			if length < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
		if len(buf[i:]) < length {
			panic(muserrs.ErrSmallBuf)
		}
		i += copy(buf[i:], v.Comment)
	}
	{
		uv := uint64(v.Kind)
		if v.Kind < 0 {
			uv = ^(uv << 1)
		} else {
			uv = uv << 1
		}
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	return i
}

// UnmarshalMUS parses the MUS-encoded buf, and sets the result to *v.
func (v *AddPendingStake) UnmarshalMUS(buf []byte) (int, error) {
	i := 0
	var err error
	{
		var sv umid.UMID
		si := 0
		si, err = sv.UnmarshalMUS(buf[i:])
		if err == nil {
			v.TransactionID = sv
			i += si
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("TransactionID", err)
	}
	{
		var sv umid.UMID
		si := 0
		si, err = sv.UnmarshalMUS(buf[i:])
		if err == nil {
			v.OdysseyId = sv
			i += si
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("OdysseyId", err)
	}
	{
		var sv PBEthAddress
		si := 0
		si, err = sv.UnmarshalMUS(buf[i:])
		if err == nil {
			v.Wallet = sv
			i += si
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Wallet", err)
	}
	{
		var sv PBUint256
		si := 0
		si, err = sv.UnmarshalMUS(buf[i:])
		if err == nil {
			v.Amount = sv
			i += si
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Amount", err)
	}
	{
		var length int
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, muserrs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, muserrs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, muserrs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			length = int(uv)
		}
		if length < 0 {
			return i, muserrs.ErrNegativeLength
		}
		if len(buf) < i+length {
			return i, muserrs.ErrSmallBuf
		}
		v.Comment = string(buf[i : i+length])
		i += length
	}
	if err != nil {
		return i, muserrs.NewFieldError("Comment", err)
	}
	{
		var uv uint64
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 9 && b > 1 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint64(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint64(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
		if uv&1 == 1 {
			uv = ^(uv >> 1)
		} else {
			uv = uv >> 1
		}
		v.Kind = int(uv)
	}
	if err != nil {
		return i, muserrs.NewFieldError("Kind", err)
	}
	return i, err
}

// SizeMUS returns the size of the MUS-encoded v.
func (v AddPendingStake) SizeMUS() int {
	size := 0
	{
		ss := v.TransactionID.SizeMUS()
		size += ss
	}
	{
		ss := v.OdysseyId.SizeMUS()
		size += ss
	}
	{
		ss := v.Wallet.SizeMUS()
		size += ss
	}
	{
		ss := v.Amount.SizeMUS()
		size += ss
	}
	{
		length := len(v.Comment)
		{
			uv := uint64(length<<1) ^ uint64(length>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
		size += len(v.Comment)
	}
	{
		uv := uint64(v.Kind<<1) ^ uint64(v.Kind>>63)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	return size
}
