// Code generated by musgen. DO NOT EDIT.

package posbus

import "github.com/ymz-ncnk/muserrs"

// MarshalMUS fills buf with the MUS encoding of v.
func (v Notification) MarshalMUS(buf []byte) int {
	i := 0
	{
		si := v.Value.MarshalMUS(buf[i:])
		i += si
	}
	return i
}

// UnmarshalMUS parses the MUS-encoded buf, and sets the result to *v.
func (v *Notification) UnmarshalMUS(buf []byte) (int, error) {
	i := 0
	var err error
	{
		var sv NotificationType
		si := 0
		si, err = sv.UnmarshalMUS(buf[i:])
		if err == nil {
			v.Value = sv
			i += si
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Value", err)
	}
	return i, err
}

// SizeMUS returns the size of the MUS-encoded v.
func (v Notification) SizeMUS() int {
	size := 0
	{
		ss := v.Value.SizeMUS()
		size += ss
	}
	return size
}
