# Shared environment vars:
x-environment: &commonEnvironment
  DEPLOYMENT: docker-compose
name: odyssey
services:
  db:
    image: postgres:15.4
    pull_policy: missing
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  controller:
    image: "${CONTAINER_REPO-ghcr.io/momentum-xyz/}ubercontroller:${VERSION_CONTROLLER:-develop}"
    build:
      context: ../../
      target: monolith
      args:
        version_controller: ${VERSION_CONTROLLER:-develop}
        version_ui: ${VERSION_UI:-develop}
    pull_policy: ${PULL_POLICY:-always}
    volumes:
      - media-data:/opt/data
    environment:
      <<: *commonEnvironment
      PGDB_HOST: "db"
      DB_PORT: "5432"
      RENDER_ASSET_PATH: /opt/data/assets
      RENDER_AUDIO_PATH: /opt/data/audio
      RENDER_IMAGE_PATH: /opt/data/images
      RENDER_VIDEO_PATH: /opt/data/video
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 5s
      timeout: 2s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
  media-data:

