// Code generated by musgen. DO NOT EDIT.

package dto

import "github.com/ymz-ncnk/muserrs"

// MarshalMUS fills buf with the MUS encoding of v.
func (v Asset3dType) MarshalMUS(buf []byte) int {
	i := 0
	{
		buf[i] = byte(v)
		i++
	}
	return i
}

// UnmarshalMUS parses the MUS-encoded buf, and sets the result to *v.
func (v *Asset3dType) UnmarshalMUS(buf []byte) (int, error) {
	i := 0
	var err error
	{
		if i > len(buf)-1 {
			return i, muserrs.ErrSmallBuf
		}
		(*v) = Asset3dType(buf[i])
		i++
	}
	return i, err
}

// SizeMUS returns the size of the MUS-encoded v.
func (v Asset3dType) SizeMUS() int {
	size := 0
	{
		_ = v
		size++
	}
	return size
}
