name: Deploy openapi spec

on:
  push:
    branches:
      - develop

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages"
  cancel-in-progress: true

jobs:
  api-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - id: go-fixup
        # Workaround for setup-go on self-hosted runner, without a $HOME
        name: Go fixup
        run: |
          echo "GOMODCACHE=/opt/go-cache/mod" >> $GITHUB_ENV
          echo "GOCACHE=/opt/go-cache/build" >> $GITHUB_ENV
          echo "GOPATH=/opt/go" >> $GITHUB_ENV
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: false  # no use on self-hosted runner
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903  # v6.0.0
        with:
          node-version: '18'
      - id: build-docs
        name: Build docs
        run: |
          go run github.com/swaggo/swag/cmd/swag@v1.8.8 init \
          -g api.go \
          -d universe/node,./,universe/streamchat \
          -o build/docs/
      - id: convert-openapi
        name: Convert to OpenAPI v3
        run: npx -- swagger2openapi@latest build/docs/swagger.json > build/docs/openapi.json
      - id: generate-html
        name: Generate HTML page
        if: github.ref == 'refs/heads/develop'
        run: npx -- @redocly/cli build-docs build/docs/openapi.json --title "Momentum controller API - development version" -o ./build/docs/api.html
      - id: store-docs
        name: Store assets catalog
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: swagger.json
          path: build/docs/swagger.json
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b  # v5.0.0
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b  # v4.0.0
        with:
          path: build/docs/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # v4.0.5
      - id: update-docs-site
        name: Update docs website
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0  # v3.0.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          token: ${{ secrets.DOCS_TRIGGER_TOKEN }}
          repository: momentum-xyz/docs
          event-type: remote-docs-update
