name: build-deploy

on:
  push:
    branches:
      - develop
      - master
      - release/*
      - v2

    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: self-hosted  # ubuntu-latest
    steps:
      - id: build
        uses: momentum-xyz/docker-build-action@ea21d97ce38d0b131c54f45cc2deb9e7ac84828c  # v6.0.3
        with:
          registry-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-user: ${{ secrets.REGISTRY_USERNAME }}
          registry-pass: ${{ secrets.REGISTRY_PASSWORD }}
          backfeed-repo-token: ${{ secrets.BACKFEED }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.build.outputs.version }}
  dev-deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/develop'
    concurrency: dev-deploy-${{ github.ref }}
    steps:
      - id: deploy-dev
        uses: momentum-xyz/deploy-action@2234fcebf5b59abe7f7f812d275abb547886ab14  # v1.1.0
        with:
          version: ${{ env.VERSION }}
          k8s-credentials: ${{ secrets[secrets.REF_K8S_DEV2] }}
  dev-v2-deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/v2'
    concurrency: dev-v2-deploy-${{ github.ref }}
    steps:
      - id: deploy-dev-v2
        uses: momentum-xyz/deploy-action@2234fcebf5b59abe7f7f812d275abb547886ab14  # v1.1.0
        with:
          version: ${{ needs.build.outputs.version }}
          k8s-credentials: ${{ secrets[vars.REF_K8S_DEV_V2] }}
  ops-deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      VERSION: ${{ needs.build.outputs.version }}
    steps:
      - id: deploy-ops
        name: Dispatch to Operations
        uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588  # v2.1.1
        with:
          token: ${{ secrets.ODYSSEY_OPERATIONS }}
          repository: momentum-xyz/Operations
          event-type: make-acc-pr
          client-payload: '{"name": "${{ env.PROJECT_NAME }}", "version": "${{ env.VERSION }}", "actor": "${{ github.event.actor.login }}"}'
