name: build-deploy

on:
  push:
    branches:
      - develop
      - master
      - release/*
      - feature/docgen

    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: self-hosted  # ubuntu-latest
    steps:
      - id: build
        uses: momentum-xyz/docker-build-action@v5
        with:
          registry-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-user: ${{ secrets.REGISTRY_USERNAME }}
          registry-pass: ${{ secrets.REGISTRY_PASSWORD }}
          backfeed-repo-token: ${{ secrets.BACKFEED }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.build.outputs.version }}
  dev-deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/develop'
    concurrency: dev-deploy-${{ github.ref }}
    steps:
      - id: deploy-dev
        uses: momentum-xyz/deploy-action@v1
        with:
          version: ${{ env.VERSION }}
          k8s-credentials: ${{ secrets[secrets.REF_K8S_DEV2] }}
  ops-deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      VERSION: ${{ needs.build.outputs.version }}
    steps:
      - id: deploy-ops
        name: Dispatch to Operations
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ODYSSEY_OPERATIONS }}
          repository: momentum-xyz/Operations
          event-type: make-acc-pr
          client-payload: '{"name": "${{ env.PROJECT_NAME }}", "version": "${{ env.VERSION }}", "actor": "${{ github.event.actor.login }}"}'
  docs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - id: go-fixup
        # Workaround for setup-go on self-hosted runner, without a $HOME
        name: Go fixup
        run: |
          echo "GOMODCACHE=/opt/go-cache/mod" >> $GITHUB_ENV
          echo "GOCACHE=/opt/go-cache/build" >> $GITHUB_ENV
          echo "GOPATH=/opt/go" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - id: build-docs
        name: Build docs
        run: |
          go run github.com/swaggo/swag/cmd/swag@v1.8.7 init \
          -g universe/node/api.go \
          -o build/docs/
      - id: store-docs
        name: Store assets catalog
        uses: actions/upload-artifact@v3
        with:
          name: swagger.json
          path: build/docs/swagger.json

