name: build-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
      - release/*

    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: self-hosted  # ubuntu-latest
    steps:
      - id: build
        uses: momentum-xyz/docker-build-action@4a172ff54dac4e9beae2a1ca8584f22d26c3c3aa # v6.3.6
        with:
          registry-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-user: ${{ secrets.REGISTRY_USERNAME }}
          registry-pass: ${{ secrets.REGISTRY_PASSWORD }}
          backfeed-repo-token: ${{ secrets.BACKFEED }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.build.outputs.version }}
  dev-deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/develop'
    concurrency: dev-deploy-${{ github.ref }}
    steps:
      - id: deploy-dev
        uses: momentum-xyz/deploy-action@d339ad4b15e98dfed06f84b49a654b43ca9a3d8a  # v1.2.0
        with:
          version: ${{ env.VERSION }}
          k8s-credentials: ${{ secrets[secrets.REF_K8S_DEV2] }}
  ops-deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      VERSION: ${{ needs.build.outputs.version }}
    steps:
      - id: deploy-ops
        name: Dispatch to Operations
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570  # v2.1.2
        with:
          token: ${{ secrets.ODYSSEY_OPERATIONS }}
          repository: momentum-xyz/Operations
          event-type: make-acc-pr
          client-payload: '{"name": "${{ env.PROJECT_NAME }}", "version": "${{ env.VERSION }}", "actor": "${{ github.event.actor.login }}"}'
