name: PR checks
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
jobs:
  checks:
    name: Checks
    runs-on: self-hosted  # ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - id: go-fixup
        # Workaround for setup-go on self-hosted runner, without a $HOME
        name: Go fixup
        run: |
          echo "GOMODCACHE=/opt/go-cache/mod" >> $GITHUB_ENV
          echo "GOCACHE=/opt/go-cache/build" >> $GITHUB_ENV
          echo "GOPATH=/opt/go" >> $GITHUB_ENV
      - uses: actions/setup-go@v4  # v4.0.1
        with:
          go-version-file: 'go.mod'
          cache: false  # does not help on self-hosted
      - name: Run tests
        run: make test
      - name: Test build
        run: make build
      - name: Check dirty git
        run: git diff --no-ext-diff --quiet
      - name: Sanity check build
        run: ./bin/ubercontroller -h
      - name: Test build docs
        run: make build-docs
