# Basically copy the values from db to controller naming
source:
  kind: Secret
  name: db-credentials
  fieldPath: data.POSTGRES_USER
targets:
  - select:
      kind: Secret
      name: momentum-db
    fieldPaths:
      - data.DB_USER=


