apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [managedByLabel]
namespace: momentum-dev
commonLabels:
  environment: dev

resources:
  - ../../base
  - namespace.yml
  - ingress.yml

components:
  - ../../components/postgresql

images:
  - name: ghcr.io/momentum-xyz/ubercontroller
    newTag: develop
  - name: ghcr.io/momentum-xyz/ui-client
    newTag: develop
  - name: postgres
    newTag: "15.4"

configMapGenerator:
  - name: controller-config
    behavior: merge
    envs:
      - controller.env

secretGenerator:
  - name: momentum-db
    behavior: replace
    envs:
      - db-auth.env

patches:
  - path: media.pvc.patch.yml
  - path: db-data.pvc.patch.yml

replacements:
  # Basically copy the values to db secret because of different naming
  - source:
      kind: Secret
      name: momentum-db
      fieldPath: data.DB_USERNAME
    targets:
      - select:
          kind: Secret
          name: db-credentials
        fieldPaths:
          - data.POSTGRES_USER
  - source:
      kind: Secret
      name: momentum-db
      fieldPath: data.DB_PASSWORD
    targets:
      - select:
          kind: Secret
          name: db-credentials
        fieldPaths:
          - data.POSTGRES_PASSWORD
  - source:
      kind: Secret
      name: momentum-db
      fieldPath: data.DB_DATABASE
    targets:
      - select:
          kind: Secret
          name: db-credentials
        fieldPaths:
          - data.POSTGRES_DB
