apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata:
- managedByLabel
namespace: momentum-dev

resources:
- ../../base
- namespace.yml
- ingress.yml

components:
- ../../components/postgresql

images:
- name: ghcr.io/momentum-xyz/ubercontroller
  newTag: develop
- name: ghcr.io/momentum-xyz/ui-client
  newTag: develop
- name: postgres
  newTag: "15.4"

configMapGenerator:
- behavior: merge
  envs:
  - controller.env
  name: controller-config

secretGenerator:
- behavior: replace
  envs:
  - db-auth.env
  name: momentum-db

patches:
- path: media.pvc.patch.yml
- path: db-data.pvc.patch.yml

  # Basically copy the values to db secret because of different naming
replacements:
- source:
    fieldPath: data.DB_USERNAME
    kind: Secret
    name: momentum-db
  targets:
  - fieldPaths:
    - data.POSTGRES_USER
    select:
      kind: Secret
      name: db-credentials
- source:
    fieldPath: data.DB_PASSWORD
    kind: Secret
    name: momentum-db
  targets:
  - fieldPaths:
    - data.POSTGRES_PASSWORD
    select:
      kind: Secret
      name: db-credentials
- source:
    fieldPath: data.DB_DATABASE
    kind: Secret
    name: momentum-db
  targets:
  - fieldPaths:
    - data.POSTGRES_DB
    select:
      kind: Secret
      name: db-credentials
labels:
- includeSelectors: true
  pairs:
    environment: dev
